// src/utils/secrets.ts

export const secrets = {
  AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  REACT_APP_AWS_REGION: 'REACT_APP_AWS_REGION',
  AWS_QUICKSIGHT_ACCOUNT_ID: 'AWS_QUICKSIGHT_ACCOUNT_ID',
  AWS_QUICKSIGHT_DASHBOARD_ID: 'AWS_QUICKSIGHT_DASHBOARD_ID',
  AWS_ATHENA_OUTPUT_LOCATION: 'AWS_ATHENA_OUTPUT_LOCATION',
};
